name: multi_vendor_customer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  #ui
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  badges: ^2.0.1
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  timeline_tile: ^2.0.0
  shimmer: ^2.0.0
  direct_select_flutter: ^1.1.1
  cached_network_image: ^3.1.0
  lottie: ^1.2.1
  firebase_core: ^1.1.0
  firebase_messaging: ^9.1.3
  flutter_local_notifications: ^5.0.0+3
  auto_size_text: ^3.0.0

  #video_player
  video_player: ^2.2.5
  youtube_player_iframe: ^2.2.2

  #state management
  provider: ^6.0.0

  #network
  dio: ^4.0.0

  #localstorage
  shared_preferences: ^2.0.7
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  #toast message
  fluttertoast: ^8.0.8

  #url management
  url_launcher: ^6.0.10

  #general
  intl: ^0.17.0
  equatable: ^2.0.3
  device_info_plus: ^3.1.0

  #routing
  go_router: ^1.1.3

  #payment gateway
  razorpay_flutter: ^1.2.7

  #pdf
  pdf: ^3.6.2
  printing: ^5.6.0
  share: ^2.0.4
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.1
  #hive database generator
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
     - payment.html
     - web/payment.html
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 900
    - family: AppIcons
      fonts:
          - asset: fonts/AppIcons.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
